Repository postmanlabs/uvm, pull requests merged in 2018-04, with the labels that each got.

#144 chore(package): update jsdoc-to-markdown to version 4.0.1
  package.json
Labels: greenkeeper

#180 chore(package): update browserify to version 16.1.1
  package.json
Labels: greenkeeper

#145 fix(package): update uuid to version 3.2.1
  package.json
Labels: greenkeeper

#179 Use `srcdoc` attribute on `iframe` for loading bootcode in browser sandbox
  CHANGELOG.md
  lib/uvm/bridge.browser.js
  test/unit/uvm-browser-large-firmware.test.js
Labels: bug

#181 Do not perform compute intensive bootcode encode multiple times
  lib/uvm/bridge.browser.js
Labels: enhancement

#183 chore(package): update eslint-plugin-jsdoc to version 3.6.2
  package.json
Labels: greenkeeper
